alias la="ls -la"
alias gs="git status"
alias gg="git graph"
alias rgrep="grep -rn --exclude-dir={tmp,log,test}"
alias c="clear"
alias vimrc="vim ~/.vimrc"
alias bashrc="vim ~/.bashrc"
alias tmrc="vim ~/.tmux_conf"
alias zshenv="vim ~/.zshenv"
alias zshrc="vim ~/.zshrc"
alias vi="vim"
